spring.application.name=CLP
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# Hibernate cria/atualiza a tabela automaticamente
spring.jpa.hibernate.ddl-auto=create

# Mostra SQL no console (opcional, mas útil para teste)
spring.jpa.show-sql=true

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

api.security.token.secret=${JWT_SECRET}