---
- name: Nmap Scan
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Executar Nmap
      command: "nmap -sV -F {{ inventory_hostname }}"
      register: nmap_result

    - name: Retornar resultado bruto
      debug:
        msg: "{{ nmap_result.stdout }}"